apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iiif-perf-results
  namespace: iiif-perf-testing
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 5Gi
